declare const classNames: {
  readonly form: "form";
  readonly selectSingleValue: "selectSingleValue";
  readonly input: "input";
  readonly radio: "radio";
  readonly checkbox: "checkbox";
  readonly checked: "checked";
  readonly label: "label";
  readonly disabled: "disabled";
  readonly selectMenu: "selectMenu";
  readonly subject: "subject";
  readonly field: "field";
  readonly hint: "hint";
  readonly error: "error";
  readonly warning: "warning";
  readonly summary: "summary";
  readonly summaryTitle: "summaryTitle";
  readonly summaryWrite: "summaryWrite";
  readonly note: "note";
  readonly blocked: "blocked";
  readonly checkboxRow: "checkboxRow";
  readonly options: "options";
  readonly optionReason: "optionReason";
  readonly readOnlyValue: "readOnlyValue";
};
export = classNames;
